version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: 
            name: Build solution
            command : | 
                dotnet restore
                dotnet build
  test_unit_testing:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: 
            name: Run tests on ChickenAPI.Packets
            command : |
                dotnet test test/ChickenAPI.Packets.Test -v m
  test_code_quality:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - run: 
            name: Test Code Quality
            command : echo "todo"
  release_nuget_packages:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: 
            name: Build ChickenAPI package (nuget)
            command : | 
                dotnet build -c Release
                dotnet pack -c Release -o nupkgs -v m
                dotnet nuget push src/ChickenAPI.Core/nupkgs/ChickenAPI.Core.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
                dotnet nuget push src/ChickenAPI.Packets/nupkgs/ChickenAPI.Packets.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
                dotnet nuget push src/ChickenAPI.Enums/nupkgs/ChickenAPI.Enums.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
                dotnet nuget push src/ChickenAPI.Data/nupkgs/ChickenAPI.Data.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
                dotnet nuget push src/ChickenAPI.Game/nupkgs/ChickenAPI.Game.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
                dotnet nuget push src/ChickenAPI.Game.Extensions/nupkgs/ChickenAPI.Game.Extensions.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_unit_testing:
          requires:
            - build
      - test_code_quality:
          requires:
            - build
      - release_nuget_packages:
          requires:
            - build
          filters:  # using regex filters requires the entire branch to match
            tags:
              only: /^\A((\d+\.)+\d+)\z/
            branches:
              ignore: /.*/
