version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: 
            name: Build solution
            command : | 
                dotnet restore
                dotnet build
  test_unit_testing:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - run: 
            name: Test Solution
            command : echo "todo"
  test_code_quality:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - run: 
            name: Test Code Quality
            command : echo "todo"
  release_nuget_package:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: 
            name: Build ChickenAPI package (nuget)
            environment: 
               PACKAGE_PATH:src/ChickenAPI.Game.Extensions/
            command : | 
                dotnet pack $PACKAGE_PATH --output nupkgs /p:PackageVersion=$CI_COMMIT_TAG
                dotnet nuget push $PACKAGE_PATH/nupkgs/ChickenAPI.$CI_COMMIT_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
      # Todo continue ChickenAPI.Game.Extensions in another repository
      - run: 
            name: Release ChickenAPI.Game.Extensions package (nuget)
            environment: 
               PACKAGE_PATH:src/ChickenAPI.Game.Extensions/
            command : | 
                dotnet pack $PACKAGE_PATH --output nupkgs /p:PackageVersion=$CI_COMMIT_TAG
                dotnet nuget push $PACKAGE_PATH/nupkgs/ChickenAPI.Extensions.$CI_COMMIT_TAG.nupkg -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test_unit_testing:
          requires:
            - build
      - test_code_quality:
          requires:
            - build
      - release_nuget_package:
          filters:  # using regex filters requires the entire branch to match
            tags:
              only: /^v.*/
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
                - develop
                - master
          requires:
            - test_code_quality
            - test_unit_testing